1. Retrieve the Top 5 Customers Who Bought the Most Books


Within the Last Year. SELECT c.customer_id,c.name,SUM(od.quantity) AS total_books_purchased
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN OrderDetails od ON o.order_id = od.order_id
WHERE o.order_date >= DATEADD(year, -1, GETDATE())
GROUP BY c.customer_id, c.name
ORDER BY total_books_purchased DESC
LIMIT 5;




2. Calculate Total Revenue Generated by Sales for Each Author


SELECT b.author, SUM(b.price * od.quantity) AS total_revenue
FROM Books b
JOIN OrderDetails od ON b.book_id = od.book_id
JOIN Orders o ON od.order_id = o.order_id
GROUP BY b.author
ORDER BY total_revenue DESC;




3. Retrieve All Books That Have Been Ordered More Than 10
Times


SELECT b.book_id, b.title, SUM(od.quantity) AS total_quantity_ordered
FROM Books b
JOIN OrderDetails od ON b.book_id = od.book_id
GROUP BY b.book_id, b.title
HAVING SUM(od.quantity) > 10
ORDER BY Y total_quantity_ordered DESC;
